rdfjs/N3.js

lib/N3Store.js, perf/N3Store-perf.js
This is an improvement for the lookup-speed of the `N3Store`, as discussed in https://github.com/rubensworks/N3.js/commit/87cae2914751c93fdeb8c005b6c445d002b6f446.
Apparently, `Object.keys` became more expensive since one of the newer Node versions,
so this PR avoids calling this function every time on `this._entities` when doing lookups.
Instead, a inverse-index is maintained to avoid this operation.
I ran the performance tests to compare this new approach with the old one,
and it resulted in some interesting results:
```
2 variables for lookups (a.k.a original perf tests):
NEW:
N3Store performance test
- Adding 16777216 triples in the default graph: 18177.111ms
* Memory usage for triples: 831MB
- Finding all 16777216 triples to the default graph 196608 times: 6421.472ms
- Adding …
```
=> Improve N3Store lookup efficiency by maintaining an inverse index

browser/build-browser-versions, package.json
The spawn commands used in the browser script were not working for windows, due to the use of the absolute paths it called the linux scripts instead of the `.cmd` windows variants.
=> Fix browser build on windows.

lib/N3Store.js
Results in slightly cleaner code, and is more optimal in the
case of many graphs.
=> Move lookup of IDs to be outside graph loop in findByIRI

lib/N3Writer.js, test/N3Writer-test.js
While processing an LOD export of the [Getty's Art & Architecture Thesaurus (AAT)](http://www.getty.edu/research/tools/vocabularies/aat/), I ran into an issue with literals accompanied by language codes that appear to be spec-compliant but are not supported by `N3Writer`.
Please review this fix and consider merging. Thanks!
=> N3Writer: Support literals with spec-conformant languages

README.md, lib/N3Store.js, test/N3Store-test.js
As requested in #145.
Note that Source#match used to accept RegExp as terms, but this has been removed now from the RDFJS spec, which simplifies implementation a lot.
I saw that #162 and #168 also offer a (partial) implementation of this, but they seem to have stalled a bit, and I need support for this ASAP, so I created this new PR (which is a bit less invasive).
=> Implement RDFJS Store (and Source) interface on N3Store

src/N3Parser.js, test/N3Parser-test.js
When no `baseIRI` is given, relative IRIs are prepended with `undefined` in the current version. I guess this is not an expected behavior. With this PR, relative IRIs are resolved against an empty string, so they are kept without changes. In an older version it was already like this and it's still possible with a workaround (`{ baseIRI: new String('') }`).
This is useful for LDP to POST to a container with relative IRIs and some other more exotic use cases.
I wasn't sure how to get the test running without big changes. @RubenVerborgh would be great if you can give me a hint how you would like to have it implemented or you just take over that part.
=> use empty string as base to support relative IRIs

src/N3Writer.js, test/N3Writer-test.js
Follows up on [#179] by taking the result of `extractLists()` as an N3Writer constructor options:
``` javascript
const lists = graph.extractLists({ remove: true });
const writer = new N3.Writer({ lists });
writer.addQuads(graph.getQuads());
```
Otherwise, the user has to do something like:
``` javascript
const listHeads = sequesterLists(graph)
const writer = new N3.Writer()
writer.addQuads(graph.getQuads().map(q => {
let members = listHeads.get(q.subject.value)
if (members)
q.subject = writer.list(members)
members = listHeads.get(q.object.value)
if (members)
q.object = writer.list(members)
return q
}))
```
=> Writer list heads

src/N3Parser.js, test/N3Parser-test.js
#182 added support for relative IRIs, but it doesn't cover the case where the IRI is empty. An error was thrown, that the IRI was invalid. This PR fixes the problem by:
- use `null` and not an empty string for invalid IRIs
- adding a test case for empty relative IRIs
From my point of view using `null` for invalid IRIs makes it more clear that something is wrong. So this PR could be also seen as a very small refactoring with the side effect of supporting empty relative IRIs :-)
=> allow empty relative IRIs

src/N3Parser.js, test/N3Parser-test.js
This makes possible to have literals as subjects; which is what the EYE reasoner is using to describe its mathematical proofs.
=> Accepts literal as subject

src/N3DataFactory.js, src/index.js, test/N3DataFactory-test.js, test/N3Store-test.js, test/Quad-test.js, test/Term-test.js
This PR implements RDF* on the data level. The changes include:
- Additional tests
- Make Quad extend Term
- Added the field 'value' to Quad which has the empty string as its value
- Added the field 'termtype' to Quad which has the value 'Quad'
- Updates to the termFromId and termToId methods that allow conversion from RDF* objects to string and back.
=> Added RDF* support by extending Quad from Term

src/N3Lexer.js, src/N3Parser.js, test/N3Lexer-test.js, test/N3Parser-test.js
- Added RDF* tests in N3Lexer-test.js
- Added RDF* tests in N3Parser-test.js
- Updated the lexer for RDF*
- Updated the parser for RDF*
This PR is based on the branch from PR #210, meaning that the changes from that PR are also listed as new changes. Those changes are:
- Additional tests for the data definitions
- Updates to the data definitions
- Updates to the termFromId and termToId methods that allow conversion from RDF* objects to string and back.
There are 2 use cases not covered by this implementation. I was not sure if they should be covered.
1)
Adding metadata over multiple triples like so:
`<<:bob foaf:age 23; foaf:knows "Mary">> creator "John" .`
2)
Quads within nested triples like so:
`<<:bob foaf:knows "Mary" graph_uri>> creator "John" .`
**Update:**
Added support for case 2: …
=> Added parsing for RDF* syntax

src/N3Writer.js, test/N3Writer-test.js
This PR adds support for writing nested quads to the Writer component of N3. The changes include
* Added a check in the method that encodes objects
* Added a method for converting subjects
* Changed the Writer to handler Quads
* Added tests
=> Extend writer for RDF* Quads

README.md
This PR aims to add documentation detailing the support of RDF* to the README file. This first version might be good but I'm open for suggestions.
There are some things I'm not sure about so I'll write them down quickly:
- As a link to RDF* I used [Olaf Hartig's position statement](https://blog.liu.se/olafhartig/2019/01/10/position-statement-rdf-star-and-sparql-star/), maybe another URL is necessary.
- I didn't mention the extensions we made to RDF* such as quads within `<< >>` yet because I was not sure where to put it, and maybe it's not necessary to mention this at all.
=> Adding documentation about RDF*

src/N3DataFactory.js, test/Quad-test.js
This allows to distinguish Quad `subject` (or `object`) value by looking at `termType` when serializing Quad to JSON.
=> Add 'termType' property to Quad.toJSON() result

.eslintrc, perf/N3Lexer-perf.js, perf/N3Parser-perf.js, src/N3Lexer.js, src/N3Parser.js, src/N3Store.js, src/N3StreamParser.js, src/N3StreamWriter.js, src/N3Util.js, src/N3Writer.js, test/BlankNode-test.js, test/DefaultGraph-test.js, test/Literal-test.js, test/N3DataFactory-test.js, test/N3Lexer-test.js, test/N3Parser-test.js, test/N3Store-test.js, test/N3StreamParser-test.js, test/N3StreamWriter-test.js, test/N3Util-test.js, test/N3Writer-test.js, test/NamedNode-test.js, test/Quad-test.js, test/Term-test.js, test/Variable-test.js
Closes #225.
Note: I stacked this branch on top of the patch-1 branch from the #223 PR.
I went ahead and changed several nested functions that were not requiring access to `this` too. Please let me know if you intended for those to remain unchanged.
Note: I did not update the nested functions in the test suite. Last time I used mocha, it was recommended not to use arrow functions. I am not sure if that is still the case. Please let me know if you would like the test suite updated to use arrow functions.
=> Switch to arrow functions

src/N3StreamWriter.js
The streamwriter currently uses a highWaterMark of 16.384, which is a value that is typically used for buffered streams. 
As a consequence, some streams may have atypical behaviour (in runtime, progress, and memory usage).
Considering this is an object stream (at least the writable part of it), I'd propose using a highWaterMark of 16 (the nodejs default)
=> [StreamWriter] Use highWaterMark of 16

src/N3Store.js, test/N3Store-test.js
DatasetCoreAndReadableStream was missing `size` required by https://rdf.js.org/dataset-spec/#datasetcore-interface
=> DatasetCoreAndReadableStream - added missing size

.gitignore, README.md, package-lock.json, package.json
As a follow up to #260, I've configured the browser build. Using this approach, `n3-browserify` won't be necessary any longer and the library will work out of the box with a url such as `https://cdn.jsdelivr.net/npm/n3`.
I tried using webpack, but the latest version doesn't include node polyfills out of the box; we'd need to use webpack 4 or configure some polyfills. So I tried using rollup instead, but the polyfills I tried didn't work either and I decided to just use browserify. It works, it's simple enough, and I don't see a reason why we wouldn't use it (after all, it's one of the suggestions in the README).
I'm sure it is possible to use webpack or rollup, but I didn't manage to make it work and I don't want to spend any more time on this. If anyone else knows more about this and …
=> Configure browser build

src/index.js
When importing n3 from an ES module in Node, the exports will be
treated as a default export, because the package itself is not an
ES module.
This _actually_ exports that default module, so that the same
syntax (i.e. importing the default export) can be used with both
Node and bundlers.
(Replaces #232 - this is what I intended to submit there.)
Fixes #196.
=> Add a default export

src/N3Lexer.js, test/N3Lexer-test.js, test/N3Parser-test.js
This PR adds the start and end index to the token object.
I would like to have the start and end index available as a N3.js consumer, because that helps to locate the exact location of parser errors. In my case, i'm using N3.js plugged into a Language Server and i want to create error markers in the editor for all parser errors - currently i always just add them add the beginning of the line as only the line information is present for tokens.
Btw, I did not adapt tests yet as i first wanted to get some feedback whether it's okay to add the start and end indices.
Greetings,
Alex
=> Add start and end index to tokens

src/N3Store.js
This skips the unnecessary step of materializing quads in an array prior to loading them into the new `N3Store`.
=> chore: use readquads in filtered (to improve perf.)

src/N3Store.js
This PR removes some now unused parameters in `_findInIndex` calls
=> chore: remove unecessary params

src/N3Store.js
Results in ~50% speedup in the 2 variable iteration case
Before
```
jeswr@debian:~/n3-benchmark/n3-opt/N3.js$ node perf/N3Store-perf.js 128
N3Store performance test
- Adding 2097152 triples to the default graph: 1.239s
* Memory usage for triples: 147MB
- Finding all 2097152 triples in the default graph 16384 times (0 variables): 4.473s
- Finding all 2097152 triples in the default graph 32768 times (1 variable): 1.357s
- Finding all 2097152 triples in the default graph 49152 times (2 variables): 1.453s
- Adding 1048576 quads: 782.903ms
* Memory usage for quads: 133MB
- Finding all 1048576 quads 131072 times: 1.223s
```
After
```
jeswr@debian:~/n3-benchmark/n3-opt/N3.js$ node perf/N3Store-perf.js 128
N3Store performance test
- Adding 2097152 triples to the default graph: 1.184s
* Memory …
```
=> performance: remove unecessary calcs

perf/.eslintrc, perf/N3Store-perf.js, src/N3Store.js
Resolves #277
This PR improves the performance `match`ing against a pattern with one defined term on graphs that are more sparsely connected. Achieving a performance improvement of `60_000`x on the degenerate case of an unconnected graph.
I have added new performance tests to demonstrate this; using a dimension of 128 the results are
Before Changes
```
N3Store performance test
- Adding 2097152 triples to the default graph: 1.269s
* Memory usage for triples: 147MB
- Finding all 2097152 triples in the default graph 16384 times (0 variables): 5.652s
- Finding all 2097152 triples in the default graph 32768 times (1 variable): 1.646s
- Finding all 2097152 triples in the default graph 49152 times (2 variables): 1.854s
- Adding 1048576 quads: 870.612ms
* Memory usage for quads: 127MB
- Finding …
```
=> performance: fix performance for cases with sparsely connected entities

.github/workflows/ci.yml, package-lock.json, package.json
It is now stable since April
Removes NodeJS 15 (not maintained anymore)
=> Adds NodeJS 18 to the CI

src/N3Lexer.js, src/N3Parser.js, test/N3Lexer-test.js, test/N3Parser-test.js
The RDF-star spec introduces syntatical suggar for annotating triples: https://w3c.github.io/rdf-star/cg-spec/editors_draft.html#annotation-syntax
=> Add support for the annotated triples syntax

.github/workflows/ci.yml, .gitignore, package-lock.json, package.json, test/.eslintrc, test/BlankNode-test.js, test/DefaultGraph-test.js, test/Literal-test.js, test/N3DataFactory-test.js, test/N3Lexer-test.js, test/N3Parser-test.js, test/N3Store-test.js, test/N3StreamParser-test.js, test/N3StreamWriter-test.js, test/N3Util-test.js, test/N3Writer-test.js, test/NamedNode-test.js, test/Quad-test.js, test/Term-test.js, test/Variable-test.js
Largely automated transformation using [jest-codemods](https://jestjs.io/docs/migration-guide) - originally did this to get better test diffs using jest-rdf to analyze https://github.com/rdfjs/N3.js/pull/364 but it turns out the spec tests are driven differently.
=> chore: migrate to jest

perf/N3StoreStar-perf.js, perf/N3StoreStarViews-perf.js, src/N3DataFactory.js, src/N3Store.js, test/N3Store-test.js, test/Term-test.js
This work was originally in https://github.com/rdfjs/N3.js/pull/341, but have pulled into a separate PR as this can be put in a patch release.
There are no performance degredations against `N3Store-perf.js`
=> fix: indexing quoted triples

.eslintrc, package-lock.json, package.json, src/N3Lexer.js
I found one line in the code where `Buffer` is used. `Buffer` is only in Node.js environments a global object and not available in the browser. Most of the time, this is probably not a problem because `readable-stream` imports the package, but in the wrong order, this may cause problems. I stumbled over this after reading the [discussion](https://github.com/rdfjs/N3.js/issues/386#issuecomment-2163881350) of recently opened issue.
This PR adds `buffer` as a dependency and adds an import in the file where `Buffer.concat()` is used. In browser environments, nothing changes. It only makes the usage of `buffer` explicit. In Node.js or other compatible environments, the implementation of `Buffer.concat()` will be a different one, but the package is from a trusted author, it is performance …
=> fix: added buffer dependency

src/N3Store.js, test/N3Store-test.js
Fixes backpressure issues on `Readable`s; currently when streams are used, the entire dataset is put into the buffer before the stream starts emitting elements.
=> perf: fix backpressure on readables

README.md, src/N3Store.js, src/N3Writer.js, test/N3Store-test.js
Draft PR to add full functionality of https://github.com/rdfjs/types/blob/master/dataset.d.ts. Observe that we alter the behavior of `#empty` on the empty set to now return `true` instead of `false`, as described in https://github.com/rdfjs/N3.js/issues/391 - so it may be that this needs to be an mver bump.
Supercedes https://github.com/rdfjs/N3.js/pull/288, pushing to a branch on the N3.js repo so CI will run.
Closes #390
Closes #391
=> feat: Implement RDF/JS dataset specification

README.md, src/N3Lexer.js, src/N3Parser.js, src/N3StreamParser.js, test/N3Parser-test.js, test/N3StreamParser-test.js
For my project I need access to the comments in a turtle (etc.) file.
This pull request:
1. extends the N3Parser.parse function with an optional commentCallback. If set, the lexer’s configuration will be overridden to also provide comment tokens.
2. extends the N3StreamParser with a "comment" event in a separate commit
=> Feature: callback and event for comments

README.md
If I’m not mistaken, `Writer.add` does not exist: only `Writer.addQuads` and `Writer.addQuad` exist.
=> Correct Writer documentation in README.md

src/N3Store.js, test/N3Store-test.js
Passes `this` as the second argument to the `some` callback to align with the RDF/JS definition of `Dataset#some`.
cc @RubenVerborgh
=> fix: align `some` with RDF/JS definition of `Dataset`
